language: java
before_install:
  - chmod +x gradlew


script:
  - ./gradlew build --info

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: heroku
  api_key:
    secure: "rHpWEj14I8Z5VJ2pBPaX/YLHdxizFyhg0LIfVd8b2Eay8xB+ykyY89lBskmIByokUkVIptG3v4xQHrt7qJJ1GX/4WsiIlLoDUiCc0pxGuGqCJPzN5mCMAdkPv3tUSJQiJIGrjjOko4ypRh/BaaMxcLOLuOEWukP09JxyOJheUVorW6nVzZynwOLkRy8CpruDT8Zsuae0QwEsxD+dLe2Ga9u0crrWnojEwtQoyqEClLzxpxbgeRqrqWiG0Y2f5cIzkSWNJO07+izk1wQBQ4GsWl1uvZDB0QzJUFCCw4BMqvFKeO0uSlEhybMXXHA3bwkh/YahLoEMiF8f9FTGibrcCUZUH0rjA0XVzHrBpSkNpzPaD8MO1f7d62uHcPgSac1jgVRodVWPuZG7aB3skzDjLkOFA6G+aAM4ry7iBlNmiLKlCdZ4jvYih8EbFSsmTh2d1vM5pHLzQG5/mdCYuGZcu8c66/tuyCeH0gmNYQNsgWBP+O4miiLCynJyPiDiqKfO0Z0h3EQ8SdToOomCDlIXSeW8udxw1UUn7fy9W9ART2M7QzMg1J/LzegekOneeI++0xzFzAcTcK6hL5gEEgllUMb17+qdXssQFVguIlcSO5w0lAEPSmtEjIgUxNr4GEJtoCUSlte1YzH5a9FQlORv2Txji0UypexeGyKfn2H9O08="
  app: tut5serv
  skip_cleanup: true
